doctrine:
    dbal:
        # configure these for your database server
        driver: "pdo_mysql"
        server_version: "8.0.31"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: "%env(resolve:DATABASE_URL)%"
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: false
        controller_resolver:
            auto_mapping: false
        entity_managers:
            default:
                quote_strategy: doctrine.orm.quote_strategy.ansi
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity"
                        prefix: 'App\Entity'
                        alias: App
                report_fields_where_declared: true
                dql:
                    string_functions:
                        if: DoctrineExtensions\Query\Mysql\IfElse
                        any_value: DoctrineExtensions\Query\Mysql\AnyValue
                    datetime_functions:
                        regexp: DoctrineExtensions\Query\Mysql\Regexp
                        date_format: DoctrineExtensions\Query\Mysql\DateFormat
                        strftime: DoctrineExtensions\Query\Sqlite\StrfTime
                        date: DoctrineExtensions\Query\Mysql\Date
                        hour: DoctrineExtensions\Query\Mysql\Hour
                        month: DoctrineExtensions\Query\Mysql\Month

when@test:
    doctrine:
        dbal:
            driver: 'pdo_sqlite'
            url: '%env(resolve:DATABASE_URL)%'
            use_savepoints: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
