pwa:
    manifest:
        enabled: true
        public_url: /site.webmanifest
        name: 'Education Management System'
        short_name: 'Education App'
        description: 'A comprehensive education management system for schools, students, and families'
        theme_color: '#007bff'
        background_color: '#ffffff'
        display: 'standalone'
        orientation: 'portrait'
        start_url: '/'
        scope: '/'
        categories:
            - education
            - productivity
        icons:
            - src: '/images/icons/icon-192x192.png'
              sizes: '192x192'
              type: 'image/png'
            - src: '/images/icons/icon-512x512.png'
              sizes: '512x512'
              type: 'image/png'

    serviceworker:
        enabled: true
        dest: /sw.js
        scope: /
        skip_waiting: true
        workbox:
            enabled: true
            use_cdn: false
            clear_cache: true
            image_cache:
                enabled: true
                cache_name: images
                max_entries: 60
                max_age: 31536000
            asset_cache:
                enabled: true
                cache_name: assets
                max_age: 31536000
            font_cache:
                enabled: true
                cache_name: fonts
                max_entries: 60
                max_age: 31536000
            warm_cache_urls:
                - '/'
                - '/login'