# see https://github.com/symfony/recipes/blob/master/symfony/security-bundle/3.3/config/packages/security.yaml
security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_ADMIN: # Un admin hérite des droits d'auteur et de modérateur
            - ROLE_DIRECTOR
            - ROLE_ACCOUNTANT
            - ROLE_STUDENT
        ROLE_DIRECTOR:
            - ROLE_TEACHER
            - ROLE_USER
            - ROLE_MEMBER
        ROLE_ADMIN_STUDENT:
            - ROLE_TEACHER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: home

            lazy: true
#            guard:
#                authenticators:
#                    - App\Security\AppAuthenticator
#
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/resetting', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/profile', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/account', roles: ROLE_ACCOUNTANT }
        - { path: '^/teacher', roles: ROLE_TEACHER }
        - { path: '^/course', roles: ROLE_TEACHER }
        - { path: '^/class-period', roles: ROLE_TEACHER }
        - { path: '^/class', roles: ROLE_TEACHER }
        - { path: '^/member', roles: ROLE_MEMBER }
        - { path: '^/meet', roles: ROLE_MEMBER }
        - { path: '^/user', roles: ROLE_SUPER_ADMIN }
