vich_uploader:
    db_driver: orm

    mappings:
        document_diploma:
            uri_prefix: /documents/diplomas
            upload_destination: '%kernel.project_dir%/public/documents/diplomas'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
