services:
  app:
    image: education:test-${GITHUB_SHA:-latest}
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://app:db_password@database:3306/education_app_test?charset=utf8mb4
      APP_SECRET: test_secret_key_for_testing_only
      CORS_ALLOW_ORIGIN: '*'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - test-network

  database:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: education_app_test
      MYSQL_USER: app
      MYSQL_PASSWORD: db_password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - test-network

networks:
  test-network:
    driver: bridge