version: "3"
services:
    app:
        build: .
        image: app
        container_name: "${PROJECT_NAME}-app"
        restart: unless-stopped
        env_file:
            - ./docker/.env.docker
        environment:
            TZ: "Europe/Paris"
        ports:
            - "${PROJECT_APP_PORT}:80"
        volumes:
            - ./docker/.env.app:/var/www/html/.env

    nice:
        image: app
        container_name: "${PROJECT_NAME}-nice"
        restart: unless-stopped
        env_file:
            - ./docker/.env.docker
        depends_on:
            - app
        environment:
            TZ: "Europe/Paris"
        ports:
            - "${PROJECT_NICE_PORT}:80"
        volumes:
            - ./docker/.env.nice:/var/www/html/.env

    db:
        image: mysql:latest
        container_name: "${PROJECT_NAME}-mysql"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${PROJECT_DB_PASSWORD}
        ports:
            - "${PROJECT_DB_PORT}:3306"
