<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\AppealCourse;
use App\Entity\ClassPeriod;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use stdClass;

/**
 * SaleProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method AppealCourse|null find($id, $lockMode = null, $lockVersion = null)
 * @method AppealCourse|null findOneBy(array $criteria, array $orderBy = null)
 * @method AppealCourse[]    findAll()
 * @method AppealCourse[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class AppealCourseRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, AppealCourse::class);
    }

    /**
     * Get list Students.
     */
    public function getAppealToClassPeriod(ClassPeriod $classPeriod, array $listStatus): stdClass
    {
        $oQuery = $this->createQueryBuilder('apc')
            ->select('apc')
            ->addSelect('cou')
            ->addSelect('std')
            ->addSelect('prs')
            ->innerJoin('apc.student', 'std')
            ->innerJoin('std.person', 'prs')
            ->innerJoin('apc.course', 'cou')
            ->innerJoin('cou.classPeriod', 'clp')
            ->where('cou.classPeriod = :classperiod')
            ->orderBy('cou.date', 'ASC')
            ->setParameter('classperiod', $classPeriod->getId())
            ->getQuery();

        $appeals = (object) [
            'courses' => [],
            'students' => [],
        ];

        $datas = $oQuery->getArrayResult();

        foreach ($listStatus as $key => $status) {
            $status['count'] = 0;

            $listStatus[$key] = $status;
        }

        foreach ($datas as $value) {
            $courseId = $value['course']['id'];
            $studentId = $value['student']['id'];
            $statusId = $value['status'];

            $value['student']['nameComplete'] = strtoupper($value['student']['person']['name']).' '.ucfirst($value['student']['person']['forname']);
            $value['course']['dateStr'] = $value['course']['date']->format('d/m');
            $value['status'] = $listStatus[$value['status']];

            if (!array_key_exists($courseId, $appeals->courses)) {
                $appeals->courses[$courseId] = (object) [
                    'course' => $value['course'],
                    'students' => [],
                ];
            }

            if (!array_key_exists($studentId, $appeals->students)) {
                $appeals->students[$studentId] = $value['student'];
                $appeals->students[$studentId]['listStatus'] = $listStatus;
                $appeals->students[$studentId]['countCOurse'] = 0;
            }

            $appeals->courses[$courseId]->students[$studentId] = $value;
            ++$appeals->students[$studentId]['countCOurse'];
            ++$appeals->students[$studentId]['listStatus'][$statusId]['count'];
        }

        return $appeals;
    }
}
