<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\ClassSchool;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ClassSchoolRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method null|ClassSchool find($id, $lockMode = null, $lockVersion = null)
 * @method null|ClassSchool findOneBy(array $criteria, array $orderBy = null)
 * @method ClassSchool[]    findAll()
 * @method ClassSchool[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class ClassSchoolRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ClassSchool::class);
    }

    /**
     * GetAvailable.
     */
    public function getQBAvailables(): QueryBuilder
    {
        return $this->createQueryBuilder('s')
            ->where('s.enable = 1')
        ;
    }
}
