dasboard:
    role: "ROLE_USER"
    icon: "fas fa-tachometer-alt"
    label: "Dashboard"
    path: "app_admin_home"

madrasse:
    role: "ROLE_TEACHER"
    icon: "fa-graduation-cap"
    label: "Madrasse"
    sub:
        student: { label: "Student", path: "app_student_index" }
        class: { label: "Class", path: "app_class_period_current" }
        family: { label: "List family", path: "app_family_index" }
        setting:
            label: Setting
            role: "ROLE_ADMIN"
            sub:
                teacher: { label: "Teacher", path: "app_teacher_index" }
                package: { label: "Package", path: "app_package_index" }

accounting:
    role: "ROLE_ACCOUNTANT"
    icon: "fa-list-ol"
    label: "Accounting"
    sub:
        account: { label: "Account", path: "app_account_index" }
        studentPayments:
            { label: "Student Payments", path: "app_student_payment_list" }
        accountSlip: { label: "Account Slip", path: "app_account_slip_index" }
        operation:
            label: "Operation"
            sub:
                Operation:
                    label: "List Operation"
                    path: "app_operation_index"
                statsOperation:
                    label: "Stats Operation"
                    path: "app_operation_statsbymonth"

setting:
    role: "ROLE_SUPER_ADMIN"
    icon: "fa-cogs"
    label: "Easy Admin"
    path: "app_admin_dashboard_index"
