app_operation_gender_root:
    path:  /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: app_operation_gender
        permanent: true

app_operation_gender:
    path:  /list/{page}/{search}
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:index", page: 1, search: '' }

app_operation_gender_show:
    path:  /{id}/show
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:show" }

app_operation_gender_new:
    path:  /new
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:new" }

app_operation_gender_create:
    path:  /create
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:create" }
    requirements: { methods: post }

app_operation_gender_edit:
    path:  /{id}/edit
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:edit" }

app_operation_gender_update:
    path:  /{id}/update
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:update" }
    requirements: { methods: post|put }

app_operation_gender_delete:
    path:  /{id}/delete
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:delete" }

app_operation_gender_search:
    path:  /search
    defaults: { _controller: "MadrasseAdminBundle:OperationGender:search" }
    requirements: { methods: post }