easy_admin:
    site_name: '<img src="/img/logo-custom.png"/ height="25rem"> Education'
    list:
        actions:
            - { name: 'show', icon: 'file', label: false, title: 'Show' }
            - { name: 'edit', icon: 'pencil', label: false, title: 'Edit' }
            - { name: 'delete', icon: 'trash', label: false, title: 'Delete' }

    design:
        brand_color: '#1ab394'
        assets:
            css:
                - 'bower/fontawesome/css/brands.css'
                - 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css'
            #js:
                #- 'inspina/js/jquery-2.1.1.js'
                #- 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js'
                # - 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js'
            favicon: '/img/logo-custom.png'
        menu:
            -   { label: 'Dashboard', route: 'app_admin_home', icon: 'home' }
            -   label: 'Education'
            -   'Course'
            -   'Grade'
            -   'Package'
            -   label: 'Student manage'
                children: ['Family', 'Student', 'StudentComment']
            -   label: 'Classes manage'
                children: ['ClassSchool', 'ClassPeriod']
            -   'School'
            -   label: 'Accountable'
            -   'TypeOperation'
            -   'OperationGender'
            -   label: 'Parameters'
            -   { entity: 'Period', permission: 'ROLE_SUPER_ADMIN' }
            -   'Document'
            -   'Structure'
            -   label: 'Persons manage'
            -   { entity: 'User', permission: 'ROLE_SUPER_ADMIN' }
            -   'Person'
            -   'Member'
