easy_admin:
    entities:
        # List the entity class name you want to manage
        StudentComment:
            class: App\Entity\StudentComment
        Student:
            class: App\Entity\Student
            form:
                fields:
                    - person.name
                    - person.forname
                    - grade
                    - lastSchool
                    - letAlone
                    - enable
                    - school

            list:
                fields:
                    - id
                    - person
                    - age
                    - letAlone
                    - grade
                    - school
                    - enable
                    - createdAt
        Person:
            class: App\Entity\Person
        Family:
            class: App\Entity\Family
            list:
                fields:
                    - id
                    - nameComplete
                    - persons
                    - numberChildren
                    - zip
                    - city
                    - enable
                    - createdAt
                    - author
        Member:
            class: App\Entity\Member
            list:
                fields:
                    - id
                    - name
                    - positionName
                    - person
                    - structure
                    - enable
                    - createdAt
                    - author
            form:
                fields:
                    - name
                    - positionName
                    - person
                    - structure
                    - enable
        Document:
            class: App\Entity\Document
            show:
                fields:
                    - id
                    - { property: path, label: 'Preview', type: 'image', base_path: '/uploads/documents/previews/'}
                    - mime
                    - extension
                    - size
                    - name
                    - school
                    - createdAt
                    - updatedAt
                    - DeletedAt
                    - enable
        Period:
            class: App\Entity\Period
        ClassSchool:
            class: App\Entity\ClassSchool
            form:
                fields:
                    - { property: name, type_options: { attr: {placeholder: 'Ex: classe 1' }}}
                    - description
                    - ageMinimum
                    - ageMaximum
                    - school
                    - enable
        ClassPeriod:
            class: App\Entity\ClassPeriod
        Structure:
            class: App\Entity\Structure
        TypeOperation:
            class: App\Entity\TypeOperation
        OperationGender:
            class: App\Entity\OperationGender
        Package:
            class: App\Entity\Package
            form:
                fields:
                    - name
                    - description
                    - price
                    - status
                    - school
        Grade:
            class: App\Entity\Grade
        Course:
            class: App\Entity\Course
            list:
                fields:
                    - id
                    - classPeriod
                    - date
                    - enable
                    - createdAt
            form:
                fields:
                    - classPeriod
                    - { property: date, type : 'App\Form\Type\DatePickerType' }
                    - hourBegin
                    - hourEnd
                    - teachers
                    - text
                    - idEvent
                    - comment
                    - enable
