easy_admin:
    entities:
        School:
            class: App\Entity\School
            show:
                fields:
                    - id
                    - name
                    - director
                    - address
                    - zip
                    - city
                    - structure
                    - packages
                    - principal
                    - enable
                    - author
                    - comment
                    - createdAt
                    - updatedAt
                    - deletedAt
            list:
                fields:
                    - id
                    - name
                    - director
                    - zip
                    - city
                    - structure
                    - principal
                    - enable
                    - createdAt
            form:
                fields:
                    - name
                    - director
                    - structure
                    - address
                    - zip
                    - city
                    - enable
                    - principal
                    - comment
