easy_admin:
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            list:
                fields:
                    - id
                    - username
                    - NameComplete
                    - username
                    - email
                    - roles
                    - enable
                    - lastLogin
            form:
                fields:
                    - username
                    - { property: 'plainPassword', type: 'password' }
                    - name
                    - surname
                    - email
                    - roles
                    - schoolAccessRight
                    - enable
